// Code generated by protoc-gen-go.
// source: downstream.proto
// DO NOT EDIT!

/*
Package seprotocol is a generated protocol buffer package.

It is generated from these files:
	downstream.proto
	upstream.proto

It has these top-level messages:
	LobbyJoinResponse
	LobbyMembership
	Downstream
	LobbyJoinRequest
	Upstream
*/
package seprotocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type LobbyJoinResponse_JoinStatusCode int32

const (
	LobbyJoinResponse_SUCCESS          LobbyJoinResponse_JoinStatusCode = 0
	LobbyJoinResponse_VERSION_MISMATCH LobbyJoinResponse_JoinStatusCode = 1
	LobbyJoinResponse_GAME_IN_PROGRESS LobbyJoinResponse_JoinStatusCode = 2
	LobbyJoinResponse_NAME_COLLISION   LobbyJoinResponse_JoinStatusCode = 3
)

var LobbyJoinResponse_JoinStatusCode_name = map[int32]string{
	0: "SUCCESS",
	1: "VERSION_MISMATCH",
	2: "GAME_IN_PROGRESS",
	3: "NAME_COLLISION",
}
var LobbyJoinResponse_JoinStatusCode_value = map[string]int32{
	"SUCCESS":          0,
	"VERSION_MISMATCH": 1,
	"GAME_IN_PROGRESS": 2,
	"NAME_COLLISION":   3,
}

func (x LobbyJoinResponse_JoinStatusCode) String() string {
	return proto.EnumName(LobbyJoinResponse_JoinStatusCode_name, int32(x))
}
func (LobbyJoinResponse_JoinStatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0}
}

type LobbyMembership_InfoType int32

const (
	LobbyMembership_COMPLETE_LIST LobbyMembership_InfoType = 0
	LobbyMembership_JOIN          LobbyMembership_InfoType = 1
	LobbyMembership_LEAVE         LobbyMembership_InfoType = 2
)

var LobbyMembership_InfoType_name = map[int32]string{
	0: "COMPLETE_LIST",
	1: "JOIN",
	2: "LEAVE",
}
var LobbyMembership_InfoType_value = map[string]int32{
	"COMPLETE_LIST": 0,
	"JOIN":          1,
	"LEAVE":         2,
}

func (x LobbyMembership_InfoType) String() string {
	return proto.EnumName(LobbyMembership_InfoType_name, int32(x))
}
func (LobbyMembership_InfoType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type LobbyJoinResponse struct {
	GameVersion    string                           `protobuf:"bytes,1,opt,name=gameVersion" json:"gameVersion,omitempty"`
	JoinStatusCode LobbyJoinResponse_JoinStatusCode `protobuf:"varint,2,opt,name=joinStatusCode,enum=seprotocol.LobbyJoinResponse_JoinStatusCode" json:"joinStatusCode,omitempty"`
	ShipID         string                           `protobuf:"bytes,3,opt,name=shipID" json:"shipID,omitempty"`
	GameID         string                           `protobuf:"bytes,4,opt,name=gameID" json:"gameID,omitempty"`
}

func (m *LobbyJoinResponse) Reset()                    { *m = LobbyJoinResponse{} }
func (m *LobbyJoinResponse) String() string            { return proto.CompactTextString(m) }
func (*LobbyJoinResponse) ProtoMessage()               {}
func (*LobbyJoinResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type LobbyMembership struct {
	InfoType     LobbyMembership_InfoType           `protobuf:"varint,1,opt,name=infoType,enum=seprotocol.LobbyMembership_InfoType" json:"infoType,omitempty"`
	LobbyMembers []*LobbyMembership_LobbyMemberInfo `protobuf:"bytes,2,rep,name=lobbyMembers" json:"lobbyMembers,omitempty"`
}

func (m *LobbyMembership) Reset()                    { *m = LobbyMembership{} }
func (m *LobbyMembership) String() string            { return proto.CompactTextString(m) }
func (*LobbyMembership) ProtoMessage()               {}
func (*LobbyMembership) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LobbyMembership) GetLobbyMembers() []*LobbyMembership_LobbyMemberInfo {
	if m != nil {
		return m.LobbyMembers
	}
	return nil
}

type LobbyMembership_LobbyMemberInfo struct {
	ShipName string `protobuf:"bytes,1,opt,name=shipName" json:"shipName,omitempty"`
}

func (m *LobbyMembership_LobbyMemberInfo) Reset()         { *m = LobbyMembership_LobbyMemberInfo{} }
func (m *LobbyMembership_LobbyMemberInfo) String() string { return proto.CompactTextString(m) }
func (*LobbyMembership_LobbyMemberInfo) ProtoMessage()    {}
func (*LobbyMembership_LobbyMemberInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 0}
}

type Downstream struct {
	LobbyJoinResponse *LobbyJoinResponse `protobuf:"bytes,1,opt,name=lobbyJoinResponse" json:"lobbyJoinResponse,omitempty"`
	LobbyMembership   *LobbyMembership   `protobuf:"bytes,2,opt,name=lobbyMembership" json:"lobbyMembership,omitempty"`
}

func (m *Downstream) Reset()                    { *m = Downstream{} }
func (m *Downstream) String() string            { return proto.CompactTextString(m) }
func (*Downstream) ProtoMessage()               {}
func (*Downstream) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Downstream) GetLobbyJoinResponse() *LobbyJoinResponse {
	if m != nil {
		return m.LobbyJoinResponse
	}
	return nil
}

func (m *Downstream) GetLobbyMembership() *LobbyMembership {
	if m != nil {
		return m.LobbyMembership
	}
	return nil
}

func init() {
	proto.RegisterType((*LobbyJoinResponse)(nil), "seprotocol.LobbyJoinResponse")
	proto.RegisterType((*LobbyMembership)(nil), "seprotocol.LobbyMembership")
	proto.RegisterType((*LobbyMembership_LobbyMemberInfo)(nil), "seprotocol.LobbyMembership.LobbyMemberInfo")
	proto.RegisterType((*Downstream)(nil), "seprotocol.downstream")
	proto.RegisterEnum("seprotocol.LobbyJoinResponse_JoinStatusCode", LobbyJoinResponse_JoinStatusCode_name, LobbyJoinResponse_JoinStatusCode_value)
	proto.RegisterEnum("seprotocol.LobbyMembership_InfoType", LobbyMembership_InfoType_name, LobbyMembership_InfoType_value)
}

var fileDescriptor0 = []byte{
	// 403 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x52, 0x5d, 0x8f, 0xd2, 0x40,
	0x14, 0xb5, 0x05, 0xb1, 0xdc, 0x6a, 0x29, 0x13, 0x63, 0x08, 0xc6, 0x84, 0x34, 0x3e, 0x90, 0xa8,
	0x7d, 0xa8, 0x7f, 0x40, 0x52, 0x27, 0x58, 0xec, 0x07, 0x99, 0x56, 0xde, 0x4c, 0x43, 0x65, 0xd4,
	0x6e, 0x4a, 0xa7, 0xa1, 0xdd, 0x6c, 0xf8, 0x05, 0xfb, 0x1f, 0xf6, 0x69, 0x7f, 0xea, 0xce, 0x14,
	0x16, 0x28, 0x24, 0xbc, 0xcd, 0x3d, 0x39, 0xe7, 0xdc, 0x7b, 0xcf, 0x5c, 0xd0, 0x57, 0xec, 0x2e,
	0x2f, 0xab, 0x0d, 0x5d, 0xae, 0xcd, 0x62, 0xc3, 0x2a, 0x86, 0xa0, 0xa4, 0xf5, 0xe3, 0x0f, 0xcb,
	0x8c, 0x07, 0x19, 0xfa, 0x2e, 0x4b, 0x92, 0xed, 0x8c, 0xa5, 0x39, 0xa1, 0x65, 0xc1, 0xf2, 0x92,
	0xa2, 0x11, 0xa8, 0xff, 0x96, 0x6b, 0xba, 0xa0, 0x9b, 0x32, 0x65, 0xf9, 0x40, 0x1a, 0x49, 0xe3,
	0x2e, 0x39, 0x85, 0x50, 0x04, 0xda, 0x0d, 0x57, 0x84, 0xd5, 0xb2, 0xba, 0x2d, 0x6d, 0xb6, 0xa2,
	0x03, 0x99, 0x93, 0x34, 0xeb, 0xb3, 0x79, 0x34, 0x37, 0x2f, 0x8c, 0xcd, 0x59, 0x43, 0x43, 0xce,
	0x3c, 0xd0, 0x3b, 0xe8, 0x94, 0xff, 0xd3, 0xc2, 0xf9, 0x3e, 0x68, 0xd5, 0x2d, 0xf7, 0x95, 0xc0,
	0x45, 0x73, 0x8e, 0xb7, 0x77, 0xf8, 0xae, 0x32, 0x7e, 0x83, 0xd6, 0x74, 0x44, 0x2a, 0xbc, 0x0a,
	0x7f, 0xd9, 0x36, 0x0e, 0x43, 0xfd, 0x05, 0x7a, 0x0b, 0xfa, 0x02, 0x93, 0xd0, 0x09, 0xfc, 0xd8,
	0x73, 0x42, 0x6f, 0x12, 0xd9, 0x3f, 0x74, 0x49, 0xa0, 0xd3, 0x89, 0x87, 0x63, 0xc7, 0x8f, 0xe7,
	0x24, 0x98, 0x12, 0xc1, 0x95, 0x11, 0x02, 0xcd, 0x17, 0xa8, 0x1d, 0xb8, 0xae, 0x23, 0x24, 0x7a,
	0xcb, 0xb8, 0x97, 0xa1, 0x57, 0xef, 0xe0, 0xd1, 0x75, 0xc2, 0x17, 0xe7, 0xc3, 0xa0, 0x6f, 0xa0,
	0xa4, 0xf9, 0x5f, 0x16, 0x6d, 0x0b, 0x5a, 0xe7, 0xa2, 0x59, 0x1f, 0x2f, 0x56, 0x3e, 0xd2, 0x4d,
	0x67, 0xcf, 0x25, 0x07, 0x15, 0x0a, 0xe0, 0x75, 0x76, 0xc2, 0xe2, 0xc1, 0xb5, 0xc6, 0xaa, 0xf5,
	0xe9, 0x9a, 0xcb, 0x49, 0x2d, 0x0c, 0x49, 0xc3, 0x60, 0xf8, 0xa5, 0x31, 0xa5, 0x20, 0xa0, 0x21,
	0x28, 0x42, 0xe8, 0xf3, 0x98, 0xf6, 0xbf, 0x77, 0xa8, 0x0d, 0x0b, 0x94, 0xe7, 0xa9, 0x50, 0x1f,
	0xde, 0xd8, 0x81, 0x37, 0x77, 0x71, 0x84, 0x63, 0xbe, 0x76, 0xc4, 0x43, 0x53, 0xa0, 0x3d, 0x0b,
	0x1c, 0x9f, 0x07, 0xd5, 0x85, 0x97, 0x2e, 0x9e, 0x2c, 0xb0, 0x2e, 0x1b, 0x8f, 0x12, 0xc0, 0xf1,
	0x8e, 0xd0, 0x4f, 0xe8, 0x67, 0xe7, 0x7f, 0x5b, 0xf7, 0x51, 0xad, 0x0f, 0x57, 0x0f, 0x80, 0x5c,
	0xea, 0x10, 0x86, 0x5e, 0xd6, 0xdc, 0xb7, 0xbe, 0x25, 0xd5, 0x7a, 0x7f, 0x25, 0x12, 0x72, 0xae,
	0x49, 0x3a, 0x35, 0xf5, 0xeb, 0x53, 0x00, 0x00, 0x00, 0xff, 0xff, 0x37, 0x26, 0xea, 0x4e, 0xf0,
	0x02, 0x00, 0x00,
}
