// Code generated by protoc-gen-go.
// source: downstream.proto
// DO NOT EDIT!

/*
Package seprotocol is a generated protocol buffer package.

It is generated from these files:
	downstream.proto
	upstream.proto

It has these top-level messages:
	JoinResponse
	LobbyMembership
	Downstream
	JoinRequest
	Upstream
*/
package seprotocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type JoinResponse_GamePhase int32

const (
	JoinResponse_LOBBY   JoinResponse_GamePhase = 0
	JoinResponse_SETUP   JoinResponse_GamePhase = 1
	JoinResponse_PLAY    JoinResponse_GamePhase = 2
	JoinResponse_CLEANUP JoinResponse_GamePhase = 3
)

var JoinResponse_GamePhase_name = map[int32]string{
	0: "LOBBY",
	1: "SETUP",
	2: "PLAY",
	3: "CLEANUP",
}
var JoinResponse_GamePhase_value = map[string]int32{
	"LOBBY":   0,
	"SETUP":   1,
	"PLAY":    2,
	"CLEANUP": 3,
}

func (x JoinResponse_GamePhase) String() string {
	return proto.EnumName(JoinResponse_GamePhase_name, int32(x))
}
func (JoinResponse_GamePhase) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type LobbyMembership_InfoType int32

const (
	LobbyMembership_COMPLETE_LIST LobbyMembership_InfoType = 0
	LobbyMembership_JOIN          LobbyMembership_InfoType = 1
	LobbyMembership_LEAVE         LobbyMembership_InfoType = 2
	LobbyMembership_NAME_CHANGE   LobbyMembership_InfoType = 3
)

var LobbyMembership_InfoType_name = map[int32]string{
	0: "COMPLETE_LIST",
	1: "JOIN",
	2: "LEAVE",
	3: "NAME_CHANGE",
}
var LobbyMembership_InfoType_value = map[string]int32{
	"COMPLETE_LIST": 0,
	"JOIN":          1,
	"LEAVE":         2,
	"NAME_CHANGE":   3,
}

func (x LobbyMembership_InfoType) String() string {
	return proto.EnumName(LobbyMembership_InfoType_name, int32(x))
}
func (LobbyMembership_InfoType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type JoinResponse struct {
	GameVersion  string                 `protobuf:"bytes,1,opt,name=gameVersion" json:"gameVersion,omitempty"`
	JoinSuccess  bool                   `protobuf:"varint,2,opt,name=joinSuccess" json:"joinSuccess,omitempty"`
	GamePhase    JoinResponse_GamePhase `protobuf:"varint,3,opt,name=gamePhase,enum=seprotocol.JoinResponse_GamePhase" json:"gamePhase,omitempty"`
	ShipServerID string                 `protobuf:"bytes,4,opt,name=shipServerID" json:"shipServerID,omitempty"`
}

func (m *JoinResponse) Reset()                    { *m = JoinResponse{} }
func (m *JoinResponse) String() string            { return proto.CompactTextString(m) }
func (*JoinResponse) ProtoMessage()               {}
func (*JoinResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type LobbyMembership struct {
	InfoType     LobbyMembership_InfoType           `protobuf:"varint,1,opt,name=infoType,enum=seprotocol.LobbyMembership_InfoType" json:"infoType,omitempty"`
	LobbyMembers []*LobbyMembership_LobbyMemberInfo `protobuf:"bytes,2,rep,name=lobbyMembers" json:"lobbyMembers,omitempty"`
}

func (m *LobbyMembership) Reset()                    { *m = LobbyMembership{} }
func (m *LobbyMembership) String() string            { return proto.CompactTextString(m) }
func (*LobbyMembership) ProtoMessage()               {}
func (*LobbyMembership) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LobbyMembership) GetLobbyMembers() []*LobbyMembership_LobbyMemberInfo {
	if m != nil {
		return m.LobbyMembers
	}
	return nil
}

type LobbyMembership_LobbyMemberInfo struct {
	ShipServerID string `protobuf:"bytes,1,opt,name=shipServerID" json:"shipServerID,omitempty"`
	ShipName     string `protobuf:"bytes,2,opt,name=shipName" json:"shipName,omitempty"`
}

func (m *LobbyMembership_LobbyMemberInfo) Reset()         { *m = LobbyMembership_LobbyMemberInfo{} }
func (m *LobbyMembership_LobbyMemberInfo) String() string { return proto.CompactTextString(m) }
func (*LobbyMembership_LobbyMemberInfo) ProtoMessage()    {}
func (*LobbyMembership_LobbyMemberInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 0}
}

type Downstream struct {
	ProtocolVersion string           `protobuf:"bytes,1,opt,name=protocolVersion" json:"protocolVersion,omitempty"`
	JoinResponse    *JoinResponse    `protobuf:"bytes,2,opt,name=joinResponse" json:"joinResponse,omitempty"`
	LobbyMembership *LobbyMembership `protobuf:"bytes,3,opt,name=lobbyMembership" json:"lobbyMembership,omitempty"`
}

func (m *Downstream) Reset()                    { *m = Downstream{} }
func (m *Downstream) String() string            { return proto.CompactTextString(m) }
func (*Downstream) ProtoMessage()               {}
func (*Downstream) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Downstream) GetJoinResponse() *JoinResponse {
	if m != nil {
		return m.JoinResponse
	}
	return nil
}

func (m *Downstream) GetLobbyMembership() *LobbyMembership {
	if m != nil {
		return m.LobbyMembership
	}
	return nil
}

func init() {
	proto.RegisterType((*JoinResponse)(nil), "seprotocol.JoinResponse")
	proto.RegisterType((*LobbyMembership)(nil), "seprotocol.LobbyMembership")
	proto.RegisterType((*LobbyMembership_LobbyMemberInfo)(nil), "seprotocol.LobbyMembership.LobbyMemberInfo")
	proto.RegisterType((*Downstream)(nil), "seprotocol.downstream")
	proto.RegisterEnum("seprotocol.JoinResponse_GamePhase", JoinResponse_GamePhase_name, JoinResponse_GamePhase_value)
	proto.RegisterEnum("seprotocol.LobbyMembership_InfoType", LobbyMembership_InfoType_name, LobbyMembership_InfoType_value)
}

var fileDescriptor0 = []byte{
	// 412 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x92, 0xc1, 0xae, 0x93, 0x40,
	0x14, 0x86, 0xa5, 0xbd, 0x2a, 0x1c, 0xf0, 0x82, 0xb3, 0x22, 0xd7, 0x4d, 0x43, 0x5c, 0x34, 0x31,
	0x61, 0x81, 0x1b, 0x17, 0x2e, 0xa4, 0x38, 0xa9, 0x34, 0x14, 0x70, 0xc0, 0x26, 0x5d, 0x35, 0xa5,
	0x8e, 0x96, 0xa6, 0x65, 0x08, 0x53, 0x35, 0x7d, 0x36, 0x7d, 0x2a, 0x9f, 0xc0, 0x81, 0xd8, 0x16,
	0xda, 0xdc, 0xee, 0x98, 0xc3, 0xff, 0x9f, 0xf9, 0xcf, 0x37, 0x07, 0x8c, 0xaf, 0xec, 0x57, 0xc1,
	0xf7, 0x15, 0x5d, 0xee, 0xec, 0xb2, 0x62, 0x7b, 0x86, 0x80, 0xd3, 0xe6, 0x63, 0xc5, 0xb6, 0xd6,
	0x5f, 0x09, 0xb4, 0x09, 0xcb, 0x0b, 0x42, 0x79, 0xc9, 0x0a, 0x4e, 0xd1, 0x00, 0xd4, 0xef, 0xcb,
	0x1d, 0x9d, 0xd1, 0x8a, 0xe7, 0xac, 0x30, 0xa5, 0x81, 0x34, 0x54, 0x48, 0xbb, 0x54, 0x2b, 0x36,
	0xc2, 0x91, 0xfc, 0x58, 0xad, 0x28, 0xe7, 0x66, 0x4f, 0x28, 0x64, 0xd2, 0x2e, 0xa1, 0x0f, 0xa0,
	0xd4, 0x86, 0x78, 0xbd, 0xe4, 0xd4, 0xec, 0x8b, 0xff, 0xf7, 0x8e, 0x65, 0x9f, 0x2f, 0xb5, 0xdb,
	0x17, 0xda, 0xe3, 0xa3, 0x92, 0x9c, 0x4d, 0xc8, 0x02, 0x8d, 0xaf, 0xf3, 0x32, 0xa1, 0xd5, 0x4f,
	0x5a, 0xf9, 0x1f, 0xcd, 0xbb, 0x26, 0x46, 0xa7, 0x66, 0xbd, 0x03, 0xe5, 0xe4, 0x45, 0x0a, 0x3c,
	0x0d, 0xa2, 0xd1, 0x68, 0x6e, 0x3c, 0xa9, 0x3f, 0x13, 0x9c, 0x7e, 0x89, 0x0d, 0x09, 0xc9, 0x70,
	0x17, 0x07, 0xee, 0xdc, 0xe8, 0x21, 0x15, 0x9e, 0x7b, 0x01, 0x76, 0x43, 0x51, 0xee, 0x5b, 0x7f,
	0x7a, 0xa0, 0x07, 0x2c, 0xcb, 0x0e, 0x53, 0xba, 0xcb, 0xc4, 0x54, 0xa2, 0xab, 0xc8, 0x2c, 0xe7,
	0xc5, 0x37, 0x96, 0x1e, 0x4a, 0xda, 0x0c, 0x7d, 0xef, 0xbc, 0x6e, 0x47, 0xbe, 0x90, 0xdb, 0xfe,
	0x7f, 0x2d, 0x39, 0xb9, 0x50, 0x04, 0xda, 0xb6, 0xa5, 0x12, 0x60, 0xfa, 0x43, 0xd5, 0x79, 0x73,
	0xab, 0x4b, 0xeb, 0x5c, 0x37, 0x24, 0x9d, 0x06, 0x0f, 0x9f, 0x3b, 0x29, 0x6b, 0xc1, 0x15, 0x17,
	0xe9, 0x9a, 0x0b, 0x7a, 0x00, 0xb9, 0x3e, 0x87, 0x82, 0x4d, 0xf3, 0x38, 0x0a, 0x39, 0x9d, 0x2d,
	0x0f, 0xe4, 0x63, 0x72, 0xf4, 0x12, 0x5e, 0x78, 0xd1, 0x34, 0x0e, 0x70, 0x8a, 0x17, 0x81, 0x9f,
	0xa4, 0x02, 0x9d, 0xe0, 0x35, 0x89, 0xfc, 0x50, 0x90, 0xab, 0x79, 0x62, 0x77, 0x86, 0x05, 0x3a,
	0x1d, 0xd4, 0xd0, 0x9d, 0xe2, 0x85, 0xf7, 0xc9, 0x0d, 0xc7, 0x58, 0xe0, 0xfb, 0x2d, 0x01, 0x9c,
	0x97, 0x0a, 0x0d, 0x41, 0x3f, 0x0e, 0xd8, 0xdd, 0x9a, 0xcb, 0x32, 0x7a, 0x0f, 0xda, 0xa6, 0xf5,
	0xf4, 0x4d, 0x3a, 0xd5, 0x31, 0x1f, 0x5b, 0x0d, 0xd2, 0x51, 0x23, 0x0c, 0xfa, 0xb6, 0xcb, 0xaf,
	0xd9, 0x2d, 0xd5, 0x79, 0x75, 0x03, 0x31, 0xb9, 0xf4, 0x64, 0xcf, 0x1a, 0xe9, 0xdb, 0x7f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x8d, 0x3f, 0xeb, 0x90, 0x18, 0x03, 0x00, 0x00,
}
