// Code generated by protoc-gen-go.
// source: ENVtoSHIP.proto
// DO NOT EDIT!

/*
Package shipenvproto is a generated protocol buffer package.

It is generated from these files:
	ENVtoSHIP.proto
	SHIPtoENV.proto

It has these top-level messages:
	LobbyJoinResponse
	LobbyMembership
	ENVtoSHIP
	LobbyJoinRequest
	SHIPtoENV
*/
package shipenvproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type LobbyJoinResponse_JoinErrorCode int32

const (
	LobbyJoinResponse_SUCCESS          LobbyJoinResponse_JoinErrorCode = 0
	LobbyJoinResponse_VERSION_MISMATCH LobbyJoinResponse_JoinErrorCode = 1
	LobbyJoinResponse_GAME_IN_PROGRESS LobbyJoinResponse_JoinErrorCode = 2
)

var LobbyJoinResponse_JoinErrorCode_name = map[int32]string{
	0: "SUCCESS",
	1: "VERSION_MISMATCH",
	2: "GAME_IN_PROGRESS",
}
var LobbyJoinResponse_JoinErrorCode_value = map[string]int32{
	"SUCCESS":          0,
	"VERSION_MISMATCH": 1,
	"GAME_IN_PROGRESS": 2,
}

func (x LobbyJoinResponse_JoinErrorCode) String() string {
	return proto.EnumName(LobbyJoinResponse_JoinErrorCode_name, int32(x))
}
func (LobbyJoinResponse_JoinErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0}
}

type LobbyMembership_InfoType int32

const (
	LobbyMembership_COMPLETE_LIST LobbyMembership_InfoType = 0
	LobbyMembership_JOIN          LobbyMembership_InfoType = 1
	LobbyMembership_LEAVE         LobbyMembership_InfoType = 2
)

var LobbyMembership_InfoType_name = map[int32]string{
	0: "COMPLETE_LIST",
	1: "JOIN",
	2: "LEAVE",
}
var LobbyMembership_InfoType_value = map[string]int32{
	"COMPLETE_LIST": 0,
	"JOIN":          1,
	"LEAVE":         2,
}

func (x LobbyMembership_InfoType) String() string {
	return proto.EnumName(LobbyMembership_InfoType_name, int32(x))
}
func (LobbyMembership_InfoType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type LobbyJoinResponse struct {
	GameVersion string                          `protobuf:"bytes,1,opt,name=gameVersion" json:"gameVersion,omitempty"`
	ErrorCode   LobbyJoinResponse_JoinErrorCode `protobuf:"varint,2,opt,name=errorCode,enum=shipenvproto.LobbyJoinResponse_JoinErrorCode" json:"errorCode,omitempty"`
	SHIPID      string                          `protobuf:"bytes,3,opt,name=SHIPID" json:"SHIPID,omitempty"`
	GameID      string                          `protobuf:"bytes,4,opt,name=GameID" json:"GameID,omitempty"`
}

func (m *LobbyJoinResponse) Reset()                    { *m = LobbyJoinResponse{} }
func (m *LobbyJoinResponse) String() string            { return proto.CompactTextString(m) }
func (*LobbyJoinResponse) ProtoMessage()               {}
func (*LobbyJoinResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type LobbyMembership struct {
	InfoType     LobbyMembership_InfoType           `protobuf:"varint,1,opt,name=infoType,enum=shipenvproto.LobbyMembership_InfoType" json:"infoType,omitempty"`
	LobbyMembers []*LobbyMembership_LobbyMemberInfo `protobuf:"bytes,2,rep,name=lobbyMembers" json:"lobbyMembers,omitempty"`
}

func (m *LobbyMembership) Reset()                    { *m = LobbyMembership{} }
func (m *LobbyMembership) String() string            { return proto.CompactTextString(m) }
func (*LobbyMembership) ProtoMessage()               {}
func (*LobbyMembership) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LobbyMembership) GetLobbyMembers() []*LobbyMembership_LobbyMemberInfo {
	if m != nil {
		return m.LobbyMembers
	}
	return nil
}

type LobbyMembership_LobbyMemberInfo struct {
	ShipName string `protobuf:"bytes,1,opt,name=shipName" json:"shipName,omitempty"`
}

func (m *LobbyMembership_LobbyMemberInfo) Reset()         { *m = LobbyMembership_LobbyMemberInfo{} }
func (m *LobbyMembership_LobbyMemberInfo) String() string { return proto.CompactTextString(m) }
func (*LobbyMembership_LobbyMemberInfo) ProtoMessage()    {}
func (*LobbyMembership_LobbyMemberInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 0}
}

type ENVtoSHIP struct {
	LobbyJoinResponse *LobbyJoinResponse `protobuf:"bytes,1,opt,name=lobbyJoinResponse" json:"lobbyJoinResponse,omitempty"`
	LobbyMembership   *LobbyMembership   `protobuf:"bytes,2,opt,name=lobbyMembership" json:"lobbyMembership,omitempty"`
}

func (m *ENVtoSHIP) Reset()                    { *m = ENVtoSHIP{} }
func (m *ENVtoSHIP) String() string            { return proto.CompactTextString(m) }
func (*ENVtoSHIP) ProtoMessage()               {}
func (*ENVtoSHIP) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ENVtoSHIP) GetLobbyJoinResponse() *LobbyJoinResponse {
	if m != nil {
		return m.LobbyJoinResponse
	}
	return nil
}

func (m *ENVtoSHIP) GetLobbyMembership() *LobbyMembership {
	if m != nil {
		return m.LobbyMembership
	}
	return nil
}

func init() {
	proto.RegisterType((*LobbyJoinResponse)(nil), "shipenvproto.LobbyJoinResponse")
	proto.RegisterType((*LobbyMembership)(nil), "shipenvproto.LobbyMembership")
	proto.RegisterType((*LobbyMembership_LobbyMemberInfo)(nil), "shipenvproto.LobbyMembership.LobbyMemberInfo")
	proto.RegisterType((*ENVtoSHIP)(nil), "shipenvproto.ENVtoSHIP")
	proto.RegisterEnum("shipenvproto.LobbyJoinResponse_JoinErrorCode", LobbyJoinResponse_JoinErrorCode_name, LobbyJoinResponse_JoinErrorCode_value)
	proto.RegisterEnum("shipenvproto.LobbyMembership_InfoType", LobbyMembership_InfoType_name, LobbyMembership_InfoType_value)
}

var fileDescriptor0 = []byte{
	// 390 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x52, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0x25, 0xdd, 0xa5, 0x24, 0x93, 0xdd, 0x6d, 0x6b, 0x21, 0x54, 0xad, 0x84, 0x58, 0xe5, 0x80,
	0x7a, 0x69, 0x0e, 0xe1, 0x17, 0x94, 0x60, 0xa5, 0x2e, 0xf9, 0x28, 0x4e, 0xc8, 0x35, 0x22, 0xc2,
	0x94, 0x48, 0x6d, 0x1c, 0x25, 0x15, 0x52, 0x7f, 0x03, 0x3f, 0x83, 0xbf, 0xc9, 0x01, 0xdb, 0xf4,
	0x23, 0x69, 0x2b, 0x38, 0xbe, 0xf1, 0xbc, 0x37, 0xf3, 0xde, 0x18, 0x06, 0x38, 0x4c, 0xb7, 0x3c,
	0x9e, 0x93, 0xa5, 0x5d, 0xd5, 0x7c, 0xcb, 0xd1, 0x5d, 0xf3, 0xbd, 0xa8, 0x58, 0xf9, 0x43, 0x21,
	0xeb, 0xb7, 0x06, 0x23, 0x9f, 0xe7, 0xf9, 0x6e, 0xc1, 0x8b, 0x92, 0xb2, 0xa6, 0xe2, 0x65, 0xc3,
	0xd0, 0x13, 0x98, 0xab, 0x2f, 0x1b, 0x96, 0xb2, 0xba, 0x29, 0x78, 0x39, 0xd6, 0x9e, 0xb4, 0x89,
	0x41, 0xdb, 0x25, 0xf4, 0x11, 0x0c, 0x56, 0xd7, 0xbc, 0x76, 0xf9, 0x57, 0x36, 0xee, 0x89, 0xf7,
	0x07, 0x67, 0x6a, 0xb7, 0x95, 0xed, 0x0b, 0x55, 0x5b, 0x02, 0x7c, 0x20, 0xd1, 0x13, 0x1f, 0xbd,
	0x82, 0xbe, 0x5c, 0x90, 0x7c, 0x18, 0xdf, 0xa8, 0x49, 0xfd, 0x46, 0x21, 0x59, 0xf7, 0xc4, 0x4c,
	0x51, 0xbf, 0xfd, 0x5b, 0x5f, 0x29, 0x64, 0xcd, 0xe1, 0xbe, 0xa3, 0x85, 0x4c, 0x78, 0x11, 0x7f,
	0x76, 0x5d, 0x1c, 0xc7, 0xc3, 0x67, 0xe8, 0x25, 0x0c, 0x53, 0x4c, 0x63, 0x12, 0x85, 0x59, 0x40,
	0xe2, 0x60, 0x96, 0xb8, 0xf3, 0xa1, 0x26, 0xab, 0xde, 0x2c, 0xc0, 0x19, 0x09, 0xb3, 0x25, 0x8d,
	0x3c, 0x2a, 0x7b, 0x7b, 0xd6, 0xcf, 0x1e, 0x0c, 0xd4, 0xa2, 0x01, 0xdb, 0xe4, 0xc2, 0x9a, 0x30,
	0x80, 0xde, 0x83, 0x5e, 0x94, 0xdf, 0x78, 0xb2, 0xab, 0x98, 0x72, 0xfe, 0xe0, 0xbc, 0xbd, 0xe2,
	0xec, 0x44, 0xb0, 0xc9, 0xbe, 0x9b, 0x1e, 0x79, 0xe8, 0x13, 0xdc, 0xad, 0x5b, 0x5d, 0x22, 0xa1,
	0x9b, 0x89, 0x79, 0x35, 0xa1, 0x96, 0x4e, 0x0b, 0x4b, 0x49, 0xda, 0x91, 0x78, 0x9c, 0x76, 0x36,
	0x95, 0x0d, 0xe8, 0x11, 0x74, 0x49, 0x0c, 0x45, 0x2a, 0xfb, 0x1b, 0x1d, 0xb1, 0xe5, 0x80, 0x7e,
	0xd8, 0x0b, 0x8d, 0xe0, 0xde, 0x8d, 0x82, 0xa5, 0x8f, 0x13, 0x9c, 0xf9, 0x24, 0x4e, 0x44, 0x48,
	0x3a, 0xdc, 0x2e, 0x22, 0x12, 0x8a, 0x60, 0x0c, 0x78, 0xee, 0xe3, 0x59, 0x8a, 0x45, 0x1a, 0xbf,
	0x34, 0x30, 0x8e, 0xdf, 0x05, 0x05, 0x30, 0x5a, 0x9f, 0xdf, 0x50, 0x8d, 0x31, 0x9d, 0x37, 0xff,
	0x39, 0x35, 0xbd, 0x64, 0x22, 0x0f, 0x06, 0xeb, 0xae, 0x61, 0xf5, 0x6f, 0x4c, 0xe7, 0xf5, 0x3f,
	0x53, 0xa1, 0xe7, 0xac, 0xbc, 0xaf, 0xfa, 0xde, 0xfd, 0x09, 0x00, 0x00, 0xff, 0xff, 0x4a, 0x85,
	0x3b, 0x62, 0xda, 0x02, 0x00, 0x00,
}
